name: $(Build.BuildId).$(Year:yy)$(DayOfYear)

trigger:
- master
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Audacia/Audacia.Build.Templates
      
steps:
- template: jobs/build/netcore/signed-package.yaml@templates
  parameters:
    packagePath: Audacia.Locality/Audacia.Locality.csproj