name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
pr: { branches: { include: [master] } }
schedules: [ { cron: "0 0 * * *", displayName: Nightly Build, branches: { include: [ master ] } } ]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }

stages:
  - stage: Build
    displayName: Build
    jobs:
    - template: pipelines/build/nuget-package.job.yaml@templates
      parameters:
        projects: Audacia.Locality/Audacia.Locality.csproj

  - stage: Release
    displayName: Release
    jobs: 
    - template: pipelines/release/internal-nuget-package.job.yaml@templates
