name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
pr: { branches: { include: [master] } }
schedules: [ { cron: "0 0 * * *", displayName: Nightly Build, branches: { include: [ master ] } } ]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build, ref: refs/heads/bugfix/missing-sn-exe } ] }

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: pipelines/build/signed-nuget-package.job.yaml@templates
    parameters: { projects: Audacia.Locality/Audacia.Locality.csproj }

- stage: Release
  displayName: Release
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
  jobs:
  - template: pipelines/release/public-nuget-package.job.yaml@templates
